name: Ryd op i GHCR

on:
  schedule:
    - cron: '0 * * * *' # Kører hver time
  workflow_dispatch: # Gør det muligt at køre den manuelt

jobs:
  delete-old-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Slet gamle versioner
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'my-ostree-os' # Skift til dit image navn
          package-type: 'container'
          min-versions-to-keep: 50
          delete-only-untagged-versions: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
